CREATE SCHEMA test;
USE test;
DROP TABLE IF EXISTS NOTES;
CREATE TABLE NOTES (NoteId INTEGER AUTO_INCREMENT PRIMARY KEY, noteName VARCHAR(50) NOT NULL, noteText VARCHAR(250), dateCreated DATE NOT NULL);