CREATE SCHEMA test;
USE test;
DROP TABLE IF EXISTS PARTS;
CREATE TABLE PARTS (id INTEGER AUTO_INCREMENT PRIMARY KEY, title VARCHAR(150) NOT NULL, i_required tinyint(1)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
